from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

if GetDepend('USING_LINUX_GNU_TOOLCHAIN'):
    group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)
else:
    group = []

objs = [group]

Return('objs')
